# Generated by Django 4.1.1 on 2022-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=55)),
                ('sender', models.EmailField(max_length=55)),
                ('reciever', models.EmailField(max_length=55)),
            ],
        ),
    ]
